version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "9092:9092"
    networks:
      - kafka-net
    depends_on:
      - zookeeper

  banking-app:
    build: .
    container_name: banking-app
    ports:
      - "8089:8089"
    networks:
      - kafka-net
    depends_on:
      - kafka
      - zookeeper
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BROKER=PLAINTEXT://kafka:9092
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092

networks:
  kafka-net:
    driver: bridge
